### ISSUE TITLE
[design] Create favicon.ico

### ISSUE THREAD

**Issue by tiagoalmeidadarosa** [tiagoalmeidadarosa/padel-appointments#18]
Description about what you need to do is in the image:

![Image](https://user-images.githubusercontent.com/20598266/219699360-44634ff7-4e58-4cb8-8d96-e6b33c8cc03a.png)

**Comment by AlexsandroVB** [comment]
![Image](https://user-images.githubusercontent.com/124370046/219800563-fa8f97ce-00ab-43b4-98df-d4036dd72bfe.png)
